# Enable mouse support
set -g mouse on

# Increase scrollback buffer size
set -g history-limit 10000

# Start window and pane numbering at 1 (more ergonomic)
set -g base-index 1
setw -g pane-base-index 1

# Rename windows to reflect current program automatically
setw -g automatic-rename on
set -g renumber-windows on

# Address vim switching delay (extremely important for vim/neovim users!)
set -s escape-time 0

# Upgrade terminal color support
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
